---
title: "Tarea 29/4"
format: html
editor: visual
---

## Tarea para el 29/4

```{r}
library(tidyverse)
my_data <- readRDS("/cloud/project/data/datos_indec.rds")
my_data$REGION %>%  unique()
```

```{r}
table(my_data$MAS_500, my_data$REGION)
```

**Crear Función**

```{r}
conjunto_de_aglomerados<-function(aglomerado){
  case_when(
    aglomerado=="N"~ "menos de 500.000 habitantes",
    aglomerado=="S"~ "igual o más de 500.000 habitantes")
}
```

**Testeo**

```{r}
conjunto_de_aglomerados("N")
```

```{r}
conjunto_de_aglomerados("S")
```

```{r}
nombrar_regiones <- function(region){
           case_when(
             region == 01 ~ "Gran Buenos Aires",
             region == 40 ~ "Noroeste",
             region == 41 ~ "Noreste",
             region == 42 ~ "Cuyo",
             region == 43 ~ "Pampeana",
             region == 44 ~ "Patagonia",
             .default = "No Encontrado")
}
```

```{r}
my_data %>%  
  mutate(REGION = nombrar_regiones(REGION)) %>% 
  select(REGION) %>%  
  head()
```

```{r}
my_data <- my_data %>%  
  mutate(Region = nombrar_regiones(REGION)) %>%  
  mutate(aglomerados = conjunto_de_aglomerados(MAS_500))
table(my_data$aglomerados,my_data$Region)
```

**Gráfico**

```{r}
my_data %>%  
  ggplot(aes(Region, fill=aglomerados))+
  geom_bar()
```
