---
title: "Tarea 22/4"
format: html
editor: visual
---

## Tarea 22/4

```{r}
library(tidyverse)
```

*Se seleccionan las columnas MAS_500 y V5*

```{r}
my_data <- readRDS("/cloud/project/data/datos_indec.rds")
my_data <- my_data %>%  
  select(MAS_500, V5)
```

*Accede a columnas específicas*

```{r}
my_data$MAS_500 %>% unique()
```

```{r}
my_data$V5 %>% unique()

```

**Limpieza de datos** (se saca lo que sería el "9")

```{r}
datos_indec %>%
  filter(V5<=2) -> tmp
table(tmp$V5)
```

**Cambio de etiqueta**

```{r}
my_data <- my_data %>%  
  mutate(ayuda = case_when(
    V5 == 1 ~ "SI",
    V5 > 1 ~ "NO"
    
  ))
```

```{r}
my_data <- my_data %>% 
  mutate(ciudades = case_when(
    MAS_500 == "S" ~ "Grandes",
    MAS_500 == "N" ~ "Pequeñas"
  ))
```

*No entiendo porque esta tabla queda así.*

```{r}
table(my_data$ayuda, my_data$ciudades)
```

**Gráfico**

```{r}
my_data %>%  
  ggplot(aes(ciudades, fill = ayuda))+
  geom_bar()
```

**Armar hipótesis:**

$H_0$ : En todas las ciudades se recibe la misma ayuda social.

$H_1$ : En las ciudades pequeñas se recibe más ayuda social.

**Comprobar hipótesis**

```{r}
table(my_data$ayuda_social, my_data$ciudades) %>% 
  chisq.test()
```
