---
author: "Lautaro Huergo"
---

# Descripción de los datos

En esta sección se realizará una descripción de cada uno de los datos analizados y utilizados de la  Encuesta Permanente de Hogares correspondiente al Instituto Nacional de Estadisticas y Censos. Se explicará en detalle la nomenclatura que fue pertienente al desarrollo de este trabajo. El objetivo de detallar estas cuestiones es permitir un mejor entendimiento al lector de lo hecho en las siguientes páginas. Es necesario aclarar, que el ya mencionado estudio del INDEC corresponde a los años 2022 y 2023, en tanto que, las variables que a continuación se detallen trabajan sobre el mencionado período. 

En tal sentido, entre otras cuestiones, el lector se encontrará con nomenclaturas que refieren a datos económicos (ingresos familiares, per capita, montos), territoriales (regiones encuestadas, aglomerados de personas por territorio), nivel educativo, de infraestructura (condiciones de habitabilidad de las personas y de los hogares), género (femenino, masculino), cantidades (miembros por familia), preguntas personales (fecha y lugar de nacimiento), etc.

Dicho esto, se puede comenzar a explicar cada uno de los datos trabajados en cada sección. Para organizar cada nomenclatura aqui detallada se utilizaran categorias a las cuales refiere cada dato. 

A) En primer lugar, el lector se encontrara con las siguientes variables de caracter económico. Las mismas están presentes en capítulos tales como "Evolución del Ingreso", "Educación e Ingreso", "Ayuda Social y "Distribución del Ingreso":

## ITF 

La misma es una variable continua que refiere al ingreso total familiar. Permite realizar un análisis en profundidad a fines de observar como han variado los ingresos de las familias argentinas en relación con la inflación de 2022 y 2023. A los objetivos de obtener el total entendimiento de lo trabajado, se podra encontrar dicha variable bajo la denominación de, "Ingreso Total Familiar" en reemplazo de su abreviatura.  

## V5_M

Este dato es posible encontrarlo a lo largo del  trabajo como "Monto_ayuda_social". Refiere a los subsidios/ayuda social total en dinero entregado por el gobierno o distintas organizaciones beneficas. Se trata de una variable económica y continua. 

## P21

Esta variable, de caracter continuo, hace referencia al monto de ingreso de la ocupación principal de cada persona encuestada. Es utilizada en el capítulo de "Brecha de Género e Ingreso".


B) Este trabajo cuenta con variables categorizadoras, entre ellas podemos mencionar:

## CODUSU

Se trata de una nomenclatura categorizadora que permite distinguir cada una de las viviendas que conforman los datos del INDEC y relacionar cada hogar con sus integrantes (personas). Variable discreta.

## AN04

Es la denominación del año de relevamiento de la información. Para una mayor comprension en este trabajo es posible encontrar la palabra "año" en referencia a este dato. Se trata de una variable discreta.


C) En tercer lugar, se trabajan nomenclaturas que en los datos del INDEC hacen referencia al territorio analizado:

## MAS_500

Es una variable discreta. La misma corresponde a conjuntos de aglomerados de habitantes. Permite organizar las muestras analiticas tomadas de cada territorio. Se subdivide en N -aquellos territorios de menos de 500.000 habitantes- y S -aglomerado de mas de 500.000 habitantes. En este caso será común encontrar la denominación "Ciudad_grande"/"Ciudad pequeña", refiere a dichos aglomerados. 


## REGION:

Variable discreta. Refiere al código de región. Es fundamental para realizar un estudio geográfico de los ingresos. Si bien para un mejor entendimiento las regiones geográficas tendrán su nombre según corresponda, el INDEC utiliza cádigos para diferenciarlas. En tal sentido, será posible encontrar en este trabajo los siguientes códigos: 

                       01 = Gran Buenos Aires
                       40 = Noroeste
                       41 = Noreste
                       42 = Cuyo
                       43 = Pampeana
                       44 = Patagonia
                       
A su vez, es común encontrar en las siguientes paginas  las etiquetas de "AMBA" e "Interior" para realizar un análisis regional comparativo a partir de los datos entre centro y periferia del país. 

## AGLOMERADO

Este termino engloba los códigos de distitas ciudades encuestadas (variabel discreta). 

                          02 = Gran La Plata
                          03 = Bahía Blanca - Cerri
                          04 = Gran Rosario
                          05 = Gram Santa Fé
                          06 = Gran Parana
                          07 = Posadas
                          08 = Gran Resistencia
                          09 = Comodoro Rivadavia - Rada Tilly
                          10 = Gran Mendoza
                          12 = Corrientes
                          13 = Gran Córdoba
                          14 = Concordia
                          15 = Formosa
                          17 = Neuquén-Plottier
                          18 = Santiago del Estero - La Banda
                          19 = Jujuy - Palpalá
                          20 = Río Gallegos
                          22 = Gran Catamarca
                          23 = Gran Salta
                          25 = La Rioja
                          26 = Gran San Luis
                          27 = Gran San Juan 
                          29 = Gram Tucumán - Tafí Viejo
                          30 = Santa Rosa - Toay
                          31 = Ushuaia - Río Grande
                          32 = Ciudad Autónoma de Buenos Aires
                          33 = Partidos del GBA
                          34 = Mar del Plata
                          36 = Río Cuarto
                          38 = San Nicolás
                          91 = Rawson - Trelew
                          93 = Vidma - Carmen de Patagones

## II7

Esta es una variable discreta que hace referencia al regimen de tenencia de cada encuestado ¿Se trata de una persona propietaria de su vivienda, de un inquilino, de alguien que solo paga expensas, de una persona que ocupa un espacio sin consentimiento o esta en un espacio gratuito?

D)  En el capitulo de "Brecha de Genero e Ingreso" se trabaja con la siguiente variable: 

## CH04

Es un dato discreto, refiere al género de cada una de las personas encuestadas. El Instituo Nacional de Estadisticas y Censos subdivide en 2 categorías, Hombre y Mujer. A lo largo del trabajo es probable encontrar a esta variable bajo la etiqueta de "Sexo". Este dato, también será utiizado en capítulos como el de "Regimen de Tenencia", "Educación e Ingreso" y "Brecha de Genero e Ingreso".


E) Variables que brindan información sobre educación:


## NIVEL_ED

Esta una variable discreta que  trata sobre el nivel educativo. Detalla si esa persona completo o no tal nivel, o si presenta instrucción.





                          
                
                          




 





