---
title: "Tarea 9"
format: html
editor: visual
---

```{r}
#| include: false
library(tidyverse)
```

```{r}
#T422_dir <- here::here("data/EPH_usu_4to_Trim_2022_txt/usu_individual_T422.txt.txt")
#T423_dir <- here::here("data/EPH_usu_4to_Trim_2023_txt/usu_individual_T423.txt")

#usu_individual_T422 <- read.table(T422_dir, header = TRUE, sep = ";", stringsAsFactors = FALSE)
#usu_individual_T423 <- read.table(T423_dir, header = TRUE, sep = ";", stringsAsFactors = FALSE)

usu_individual_T422 <- readRDS(here::here("data/usu_individual_T422.rds"))
usu_individual_T423 <- readRDS(here::here("data/usu_individual_T423.rds"))
```

```{r}
source(here::here("R/agregar-uid.R"))

usu_individual_T422 <- usu_individual_T422 |>
  agregar_uid_individual()
usu_individual_T423 <- usu_individual_T423 |>
  agregar_uid_individual()

```

```{r}
usu_individual_T422 |> 
  filter(V5_M > 0) |> 
  nrow()
usu_individual_T423 |> 
  filter(V5_M > 0) |> 
  nrow()
```

```{r}
UIDs <- intersect(usu_individual_T422$UID,usu_individual_T423$UID)

usu_individual_T422_filtrado <- usu_individual_T422 |>
  filter(UID %in% UIDs) |> 
  arrange(CODUSU) |> 
  select(Año = ANO4, Region = REGION, Ciudad_grande = MAS_500, Aglomerado = AGLOMERADO, Sexo = CH04, Monto_ayuda_social = V5_M)
  
usu_individual_T423_filtrado <- usu_individual_T423 |>
  filter(UID %in% UIDs) |> 
  arrange(CODUSU) |> 
  select(Año = ANO4, Region = REGION, Ciudad_grande = MAS_500, Aglomerado = AGLOMERADO, Sexo = CH04, Monto_ayuda_social = V5_M)
```

```{r}
source(here::here("R/nombrar_aglomerados.R"))
source(here::here("R/nombrar-regiones.R"))

usu_individual_T422_filtrado <- usu_individual_T422_filtrado |> 
  mutate(Region = nombrar_regiones(Region)) |>
  mutate(Aglomerado = nombrar_aglomerados(Aglomerado)) |>
  mutate(Ciudad_grande = case_when(
    Ciudad_grande == "S" ~ "Si",
    Ciudad_grande == "N" ~ "No"
  ))

usu_individual_T423_filtrado <- usu_individual_T423_filtrado |> 
  mutate(Region = nombrar_regiones(Region)) |>
  mutate(Aglomerado = nombrar_aglomerados(Aglomerado)) |>
  mutate(Ciudad_grande = case_when(
    Ciudad_grande == "S" ~ "Si",
    Ciudad_grande == "N" ~ "No"
  ))

usu_individual_T422_filtrado
```

```{r}
usu_individual_T422_T423_f <- bind_rows(
  usu_individual_T422_filtrado,
  usu_individual_T423_filtrado 
)

usu_individual_T422_T423_f
```

```{r}
source(here::here("R/graficar_ayuda_social_2022_2023.R"))

usu_individual_T422_T423_f |> 
  filter(Monto_ayuda_social > 0) |> 
  graficar_ayuda_social_2022_2023()

```

```{r}
ajuste_por_inflacion <- 1 + (211.4 / 100)

usu_individual_T422_T423_f |> 
  mutate(Monto_ayuda_social = ifelse(Año == 2022, Monto_ayuda_social * ajuste_por_inflacion, Monto_ayuda_social)) |> 
  filter(Monto_ayuda_social > 0) |> 
  graficar_ayuda_social_2022_2023()
```
