---
title: "Tarea clase 15-4"
format: html
editor: visual
---

## Tarea para el 15-4-24

Realizar un análisis de diferencias entre regiones argentinas (Las 6):

-   Generar una tabla con los promedios (media y mediano) y medidas de disperción por region.

-   Graficar ls curva de distribución del ingreso por cada región. (Ojo: hacelo en un solo plot).

-   Interpretar los resultados

-   Formular hipótesis

```{r}
library(tidyverse)
my_data <- readRDS("/cloud/project/data/datos_indec.rds")
```

```{r}
## Columnas
temp_df <- my_data |> 
  select(REGION, IPCF)
```

```{r}
temp_df
```

```{r}
## Filas
temp_df |> 
  filter(REGION == 1)
```

```{r}
## Agregar nombres de región
temp_df <- temp_df |>
  mutate(REGION2 =
          case_when(
            REGION == 1 ~ "Gran Buenos Aires",
            REGION != 1 ~ "Interior",
            .default = "No Encontrado"))
temp_df
```

```{r}
## Modificar nombres a las 6 regiones, más específicos
temp_df <- temp_df |>
  mutate(REGION2 =
           case_when(
             REGION == 01 ~ "Gran Buenos Aires",
             REGION == 40 ~ "Noroeste",
             REGION == 41 ~ "Noreste",
             REGION == 42 ~ "Cuyo",
             REGION == 43 ~ "Pampeana",
             REGION == 44 ~ "Patagonia",
             REGION != 01 ~ "Interior",
             .default = "No Encontrado"))
temp_df
```

```{r}
## MEDIA Y MEDIANA DE CADA REGIÓN
temp_df |>
  group_by(NOMBREREGION) |>
  summarise(
    MEDIA = mean(IPCF),
    MEDIANA = median(IPCF)
  )
```

```{r}
## TABLA DE PROMEDIOS - TAREA 
```

```{r}
## PONER COLORES
temp_df |>
  group_by(
    IPCF = mean(IPCF)
  )|>
  ggplot(aes(x=REGION2,y=IPCF, fill = REGION2))+
  geom_col()
```

```{r}
## HACER UN HISTOGRAMA POR INGRESO
```

```{r}
## CURVA
temp_df |>
  filter(IPCF<1000000) |>
  ggplot(aes(IPCF))+
  geom_density()
```

```{r}
## PONER COLOR
temp_df |>
filter(IPCF<1000000) |>
  ggplot(aes(IPCF, fill = REGION2))+
  geom_density()
```

```{r}
## SEPARAR EN DISTINTOS CUADROS
temp_df |>
  filter(IPCF<1000000) |>
  ggplot(aes(IPCF, fill = REGION2))+
  geom_density(alpha=.5)+
  facet_wrap( ~REGION2)
```

```{r}
##
temp_df |> 
  filter(IPCF<1000000) |>
  ggplot(aes(IPCF, fill = REGION2))+
  geom_density()+
  facet_wrap(~REGION2, ncol = 1)
```

```{r}
##
temp_df |> 
  filter(IPCF<1000000) |>
  ggplot(aes(IPCF, color = REGION2, fill = REGION2))+
  geom_density()+
  facet_wrap(~REGION2, ncol = 1)
```

```{r}
##
temp_df |> 
  filter(IPCF<1000000) |>
  ggplot(aes(IPCF, color = REGION2, fill = REGION2))+
  geom_density()+
  facet_wrap(~REGION2, ncol = 1)+theme_bw()
```

```{temp_df |>}
  filter(IPCF<1000000) |>
  ggplot(aes(IPCF))+
  geom_histogram()
```

```{temp_df |>}
  group_by(REGION2) |>
  summarise(
    IPCF = mean(IPCF)
    )|>
  ggplot(aes(x=REGION2,y=IPCF))+
  geom_col()
```

```{r}
## INTERPRETACIÓN DE RESULTADOS E HIPÓTESIS
```

## Lectura

-   Capítulo 6 del libro.
