---
title: "tarea 29-4 ok"
format: html
editor: visual
---

### Tarea

```{r}
library(tidyverse)
my_data <- readRDS("/cloud/project/data/datos_indec.rds")
my_data$II7 %>% unique()
```

```{r}
my_data <- my_data %>% filter(II7 !=9)
my_data <- my_data %>% filter(II7 !=0)
table(my_data$II7)

```

```{r}
nombrar_tenencias <- function(tenencia){
  case_when(
             tenencia == 1 ~ "Propietario de la vivienda y el terreno",
             tenencia == 2 ~ "Propietario de la vivienda solamente",
             tenencia == 3 ~ "Inquilino",
             tenencia == 4 ~ "Ocupante por pago de impuestos y expensas",
             tenencia == 5 ~ "Ocupante en relación de dependencia",
             tenencia == 6 ~ "Ocupante gratuito con permiso",
             tenencia == 7 ~ "Ocupante de hecho sin permiso",
             tenencia == 8 ~ "Está en sucesión"
             )
}
```

Testeo

```{r}
nombrar_tenencias(1)
nombrar_tenencias(5)
nombrar_tenencias(3)
nombrar_tenencias(6)
nombrar_tenencias(4)
```

```{r}
my_data$II7 |> unique()

my_data_transformada <- my_data %>% 
  mutate(tenencia = nombrar_tenencias(II7)) %>% 
  select(tenencia)

my_data_transformada$tenencia |> unique()
```

```{r}
my_data_transformada %>%
  ggplot(aes(tenencia, fill=tenencia))+
  geom_bar() # a diferencia de geom_col, geom_bar cuenta...
         
```

```{r}
my_data_transformada |> 
  group_by(tenencia) |> 
  count() |> 
  ggplot(aes(tenencia,n, fill=tenencia))+
  geom_col()
```
